import { MusicToChoose } from "@/interface/Music";

export const initialSongs: MusicToChoose[] = [
  {
    name: "1-800-273-8255",
    author: "Logic",
    url: "/1-800-273-8255-cover.jpeg",
    emotions: {
      dating: "Very Low",
      violence: "Very Low",
      "world/life": "Very Low",
      "night/time": "Very Low",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "Low",
      communication: "Very Low",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Very Low",
      feelings: "Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Very Low",
      energy: "Very Low",
    },
  },
  {
    name: "7 years",
    author: "Lukas Graham",
    url: "/7-years-cover.jpeg",
    emotions: {
      dating: "High",
      violence: "Very Low",
      "world/life": "Very Low",
      "night/time": "High",
      "shake the audience": "High",
      "family/gospel": "High",
      romantic: "Very Low",
      communication: "Very Low",
      obscene: "Very Low",
      music: "Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "High",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Very Low",
      energy: "Very Low",
    },
  },
  {
    name: "can i be him",
    author: "James Arthur",
    url: "/can-i-be-him-cover.jpeg",
    emotions: {
      dating: "High",
      violence: "Very Low",
      "world/life": "Very Low",
      "night/time": "High",
      "shake the audience": "High",
      "family/gospel": "High",
      romantic: "Very Low",
      communication: "Very Low",
      obscene: "Very Low",
      music: "Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "High",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Very Low",
      energy: "Very Low",
    },
  },
  {
    name: "chunky",
    author: "Bruno Mars",
    url: "/chunky-cover.jpeg",
    emotions: {
      dating: "Low",
      violence: "Very Low",
      "world/life": "Very Low",
      "night/time": "Medium",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "Very Low",
      communication: "Very Low",
      obscene: "Medium",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Very Low",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Low",
      instrumentalness: "Very Low",
      valence: "Very Low",
      energy: "Very Low",
    },
  },
  {
    name: "copycat",
    author: "Billie Eilish",
    url: "/copycat-cover.jpeg",
    emotions: {
      dating: "Very Low",
      violence: "Very Low",
      "world/life": "Very Low",
      "night/time": "Very Low",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "Very Low",
      communication: "Medium",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Very Low",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Low",
      energy: "High",
    },
  },
  {
    name: "happier",
    author: "Ed Sheeran",
    url: "/happier-cover.jpeg",
    emotions: {
      dating: "Very Low",
      violence: "Very Low",
      "world/life": "Very Low",
      "night/time": "Very Low",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "Very Low",
      communication: "Low",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Medium",
      feelings: "Very Low",
      danceability: "Very High",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Low",
      energy: "Very Low",
    },
  },
  {
    name: "history",
    author: "One Direction",
    url: "/history-cover.png",
    emotions: {
      dating: "Very Low",
      violence: "Very Low",
      "world/life": "Medium",
      "night/time": "Very Low",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "Very Low",
      communication: "Very Low",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Medium",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Very Low",
      energy: "Very Low",
    },
  },
  {
    name: "ho hey",
    author: "The Lumineers",
    url: "/ho-hey-cover.jpeg",
    emotions: {
      dating: "Low",
      violence: "Very Low",
      "world/life": "Very Low",
      "night/time": "Very Low",
      "shake the audience": "Low",
      "family/gospel": "Low",
      romantic: "Very Low",
      communication: "Very Low",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Low",
      "like/girls": "Very Low",
      sadness: "Low",
      feelings: "Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Medium",
      energy: "Very Low",
    },
  },
  {
    name: "layla (with j. j. cale)",
    author: "Eric Clapton",
    url: "/layla-cover.jpeg",
    emotions: {
      dating: "Very Low",
      violence: "Very Low",
      "world/life": "Low",
      "night/time": "Very Low",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "Very Low",
      communication: "Very Low",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Very Low",
      feelings: "Very Low",
      danceability: "Medium",
      loudness: "Very Low",
      acousticness: "Low",
      instrumentalness: "Very Low",
      valence: "High",
      energy: "Very Low",
    },
  },
  {
    name: "mercy",
    author: "Shawn Mendes",
    url: "/mercy-cover.jpeg",
    emotions: {
      dating: "Very Low",
      violence: "Very Low",
      "world/life": "Very Low",
      "night/time": "Very Low",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "Low",
      communication: "Low",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Medium",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Medium",
      energy: "Very Low",
    },
  },
  {
    name: "paris",
    author: "The Chainsmokers",
    url: "/paris-cover.png",
    emotions: {
      dating: "Very Low",
      violence: "Very Low",
      "world/life": "Very Low",
      "night/time": "Very Low",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "Low",
      communication: "Low",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Very Low",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Low",
      energy: "Very Low",
    },
  },
  {
    name: "sorry for party rocking",
    author: "LMFAO",
    url: "/party-rock-cover.jpeg",
    emotions: {
      dating: "Low",
      violence: "Very Low",
      "world/life": "Very Low",
      "night/time": "Very Low",
      "shake the audience": "Very Low",
      "family/gospel": "Medium",
      romantic: "Medium",
      communication: "Low",
      obscene: "Very Low",
      music: "Medium",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Medium",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Low",
      instrumentalness: "Very Low",
      valence: "Very Low",
      energy: "Very Low",
    },
  },
  {
    name: "payphone",
    author: "Maroon 5",
    url: "/payphone-cover.jpeg",
    emotions: {
      dating: "Medium",
      violence: "Medium",
      "world/life": "Very Low",
      "night/time": "Very Low",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "Medium",
      communication: "Low",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Medium",
      "light/visual perceptions": "High",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Low",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Low",
      instrumentalness: "Very Low",
      valence: "High",
      energy: "Very Low",
    },
  },
  {
    name: "pretty hurts",
    author: "Beyoncé",
    url: "/pretty-hurts-cover.jpeg",
    emotions: {
      dating: "Very Low",
      violence: "Very Low",
      "world/life": "Medium",
      "night/time": "Very Low",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "Very Low",
      communication: "Very Low",
      obscene: "Medium",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Low",
      "family/spiritual": "Medium",
      "like/girls": "Low",
      sadness: "Medium",
      feelings: "Very Low",
      danceability: "Very High",
      loudness: "Very Low",
      acousticness: "Low",
      instrumentalness: "Very Low",
      valence: "Low",
      energy: "Very Low",
    },
  },
  {
    name: "psycho pt. 2",
    author: "Russ",
    url: "/psycho-pt-2-cover.png",
    emotions: {
      dating: "Low",
      violence: "Very Low",
      "world/life": "Low",
      "night/time": "Very Low",
      "shake the audience": "Low",
      "family/gospel": "Very Low",
      romantic: "Very Low",
      communication: "Very Low",
      obscene: "Low",
      music: "Very Low",
      "movement/places": "High",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "High",
      sadness: "Very Low",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Very Low",
      energy: "Very Low",
    },
  },
  {
    name: "radioactive",
    author: "Imagine Dragons",
    url: "/radioactive-cover.jpeg",
    emotions: {
      dating: "Very Low",
      violence: "Medium",
      "world/life": "Very Low",
      "night/time": "Very Low",
      "shake the audience": "Low",
      "family/gospel": "Very Low",
      romantic: "Very Low",
      communication: "Very Low",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Very Low",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Low",
      energy: "Very Low",
    },
  },
  {
    name: "what they want",
    author: "Russ",
    url: "/what-they-want-cover.png",
    emotions: {
      dating: "Very Low",
      violence: "Low",
      "world/life": "Very Low",
      "night/time": "High",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "Very Low",
      communication: "Very Low",
      obscene: "Medium",
      music: "High",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "High",
      "like/girls": "Very Low",
      sadness: "High",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "High",
      energy: "High",
    },
  },
  {
    name: "whatever it takes",
    author: "Imagine Dragons",
    url: "/whatever-it-takes-cover.jpeg",
    emotions: {
      dating: "Very Low",
      violence: "Low",
      "world/life": "Very Low",
      "night/time": "Very Low",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "Very Low",
      communication: "Very Low",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Medium",
      feelings: "Very Low",
      danceability: "Very High",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Very Low",
      energy: "Very Low",
    },
  },
  {
    name: "young wild & free (feat. bruno mars)",
    author: "Snoop Dogg",
    url: "/young-wild-and-free-cover.jpeg",
    emotions: {
      dating: "Medium",
      violence: "Medium",
      "world/life": "Very Low",
      "night/time": "Medium",
      "shake the audience": "Very Low",
      "family/gospel": "Medium",
      romantic: "Medium",
      communication: "Very Low",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Low",
      "light/visual perceptions": "Medium",
      "family/spiritual": "Very Low",
      "like/girls": "Medium",
      sadness: "Very Low",
      feelings: "Very Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Very Low",
      instrumentalness: "Very Low",
      valence: "Very Low",
      energy: "Very Low",
    },
  },
  {
    name: "your body is a wonderland",
    author: "John Mayer",
    url: "/your-body-is-a-wonderland-cover.jpeg",
    emotions: {
      dating: "Low",
      violence: "Medium",
      "world/life": "Very Low",
      "night/time": "Very Low",
      "shake the audience": "Very Low",
      "family/gospel": "Very Low",
      romantic: "High",
      communication: "Very Low",
      obscene: "Very Low",
      music: "Very Low",
      "movement/places": "Very Low",
      "light/visual perceptions": "Very Low",
      "family/spiritual": "Very Low",
      "like/girls": "Very Low",
      sadness: "Very Low",
      feelings: "Low",
      danceability: "Very Low",
      loudness: "Very Low",
      acousticness: "Low",
      instrumentalness: "Very Low",
      valence: "Very Low",
      energy: "Very Low",
    },
  },
];
